package database;

public class HTMLoldalak {

    /**
     * A HTML oldalak string formátumban
     *
     * @param szama (A keresett oldal hódjának sorszáma)
     * @return (a paraméterként adott számú htmlkód Stringben )
     *
     * @see 0-regisztracio
     *
     * @see 1-warning
     *
     * @see 2-reg2
     *
     * @see 3-admin
     *
     * @see 4-password
     *
     * @see 5-receptiras
     *
     * @see 6-bejelentkezve
     *
     * @see 7-kerdes
     *
     * @see 8-alapanyag_hozzaadas
     *
     * @see 9-receptjeim
     * 
     * @see 10-alapfejléc
     */
    public String oldal_kerese(int szama) {

        String[] taroltoldal = {"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n"
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Regisztráció</title>\n"
            + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "    <script type=\"text/javascript\" src=\"scr/reg.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"startTime();\">\n"
            + "   <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "          <br>\n"
            + "          <span class=\"style8\">Regisztált felhasználóknak személyes receptadatbázis, saját alapanyagadatbázis kialakításának, megosztásának lehetőségével </span><br>\n"
            + "        </p>\n"
            + "    </div>\n"
            + "    <table width=\"1091\" height=\"144\" border=\"3\" align=\"center\" bordercolor=\"#CCCC99\" bgcolor=\"#AA9F55\">\n"
            + "      <tr>\n"
            + "        <td width=\"1077\" height=\"134\"><table width=\"1059\" height=\"101\" border=\"2\" align=\"center\" bordercolor=\"#2A0000\">\n"
            + "            <tr>\n"
            + "              <td width=\"174\" height=\"97\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p class=\"style4\"> Információk</p>\n"
            + "                  <form name=\"form5\" method=\"post\" action=\"info\">\n"
            + "                    <label>\n"
            + "                    <input name=\"info\" type=\"submit\" class=\"sidebarHeader\" id=\"info\" tabindex=\"5\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"198\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Online kalkulátorok</p>\n"
            + "                  <form name=\"form4\" method=\"post\" action=\"kalk\">\n"
            + "                    <label>\n"
            + "                    <input name=\"kalk\" type=\"submit\" class=\"sidebarHeader\" id=\"kalk\" tabindex=\"4\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"199\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Segédanyagok </p>\n"
            + "                  <form name=\"form4\" method=\"post\" action=\"segedlet\">\n"
            + "                 \n"
            + "                      <label>\n"
            + "                      <input name=\"alkalmazasok\" type=\"submit\" class=\"sidebarHeader\" id=\"alkalmazasok\" tabindex=\"3\" value=\"Tovább\">\n"
            + "                      </label>\n"
            + "                 \n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"230\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Keresés az adatbázisban </p>\n"
            + "                  <form name=\"form2\" method=\"post\" action=\"keresesek\">\n"
            + "                    <label>\n"
            + "                    <input name=\"kereses\" type=\"submit\" class=\"sidebarHeader\" id=\"kereses\" tabindex=\"2\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"222\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Regisztráció</p>\n"
            + "                  <form name=\"form1\" method=\"post\" action=\"Login\">\n"
            + "                    <label>\n"
            + "                    <input name=\"login\" type=\"submit\" class=\"sidebarHeader\" id=\"regisztralas\" tabindex=\"1\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "            </tr>\n"
            + "        </table></td>\n"
            + "      </tr>\n"
            + "    </table>\n"
            + "    <br>\n"
            + "	\n"
            + "    <table width=\"625\" height=\"438\" border=\"5\" align=\"center\" cellpadding=\"5\" bordercolor=\"#AA9F55\">\n"
            + "        <tr>\n"
            + "            <th width=\"599\" height=\"426\" nowrap  >\n"
            + "                  <div align=\"right\">\n"
            + "                        <p align=\"center\">\n"
            + "                          <label class=\"legal\"><span class=\"style6\">Regisztrációs adatok és ellenörzés </span><br>\n"
            + "                          </label>\n"
            + "                        </p>\n"
            + "                        <p>\n"
            + "						<form name=\"form6\" method=\"post\" onsubmit=\"return validateForm()\" action=\"beregisztral\">\n"
            + "                          		<p>\n"
            + "                          		  <input id =\"a1\" name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "								  \n"
            + "								  <div id=\"pp1\"></div>\n"
            + "									<div id=\"pp2\"></div>\n"
            + "									<div id=\"nn1\"></div>\n"
            + "									<div id=\"ee1\"></div>\n"
            + "									<div id=\"a1\"></div>\n"
            + "</p>\n"
            + "                          		<p>&nbsp;                                </p>\n"
            + "                          		<div align=\"right\">\n"
            + "                                        <p>\n"
            + "                                          <label><span class=\"style3\">E-mail cím (kötelező)</span>                                          <input id=\"n1\" name=\"neve\" type=\"email\" tabindex=\"6\">\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Felhasználói név (kötelező)</span>                                          <input id=\"e1\" name=\"email\" type=\"text\" tabindex=\"7\">\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Jelszó (kötelező minimum 6 karakter)</span>                                          <input id=\"p1\" type=\"password\" name=\"pw1\" tabindex=\"8\">\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Jelszó megismétlése (kötelező)</span>                                          <input id=\"p2\" type=\"password\" name=\"pw2\" tabindex=\"9\">\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Webcím (Blog,Facebook...,opcionális)</span>                                          <input type=\"url\" name=\"web\" tabindex=\"10\">\n"
            + "                                          <br>\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Egyéb megosztható információk (opcionális)</span></label>\n"
            + "                                        </p>\n"
            + "                                        <p>\n"
            + "                                          <label>                                          \n"
            + "                                          <textarea name=\"rolam\" cols=\"80\" rows=\"5\" tabindex=\"11\"></textarea>\n"
            + "                                          <br>\n"
            + "                                          <span class=\"style3\">Írja be a  művelet eredményét: eztkelllecserelni=</span>                                          <input name=\"eredmeny\" type=\"text\" tabindex=\"12\">\n"
            + "                                                  </label>\n"
            + "                                        </p>\n"
            + "                   		  </div>\n"
            + "                                      <p align=\"center\">\n"
            + "                             <label class=\"style3\"><a href=\"licenc/junit.pdf\">Regisztrációs feltételek </a></label>\n"
            + "                          </p>\n"
            + "                                      <p align=\"center\">\n"
            + "                                        <label class=\"style3\">\n"
            + "                               <input name=\"elfogadom\" type=\"checkbox\" tabindex=\"13\"  value=\":##:\">\n"
            + "                               <span class=\"style12\"> Elfogadom a feltételeket</span></label>\n"
            + "						                </p>\n"
            + "                                      <div align=\"center\">\n"
            + "                             <label><span class=\"style3\">Regisztrácio</span>́\n"
            + "                             <input name=\"regisztralas\" type=\"submit\" class=\"style9\" id=\"regisztralas\" tabindex=\"14\" value=\"Indítása\">\n"
            + "						    \n"
            + "                           </label>\n"
            + "                           </div>\n"
            + "                           <label></label>\n"
            + "           </form>\n"
            + "          \n"
            + "      </tr>\n"
            + "</table>\n"
            + "          <br>\n"
            + "    <table width=\"1209\" height=\"41\" border=\"1\" align=\"center\">\n"
            + "        <tr>\n"
            + "            <td width=\"1199\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "                    <div align=\"center\"><div id=\"txt\"></div> </div>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //------------figyelem
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Figyelem!</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "    <script type=\"text/javascript\">\n"
            + "	function mouseOver(id)\n"
            + "	{\n"
            + "		if(id==\"fooldalra\"){\n"
            + "			document.getElementById(id).value =\"Kattintás\";\n"
            + "		}\n"
            + "		else document.getElementById(id).value =\"Kattintás\";\n"
            + "	}\n"
            + "	function mouseOut(id)\n"
            + "	{\n"
            + "		if(id==\"fooldalra\"){\n"
            + "			document.getElementById(id).value =\"Vissza a főoldalra\";\n"
            + "		}\n"
            + "		else document.getElementById(id).value =\"Tovább\";\n"
            + "	}\n"
            + "</script>\n"
            + "	</head>\n"
            + "<body>\n"
            + " "   
            + "    </table>\n"
            + "    <br>    \n"
            + "     <table width=\"845\" height=\"400\" border=\"0\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#AA9F55\" bgcolor=\"#DEDECA\">\n"
            + "        <tr bgcolor=\"#F0F0F0\">\n"
            + "          <td width=\"827\" height=\"400\" bordercolor=\"#D40000\" bgcolor=\"#CAE470\" class=\"style8\"><div align=\"center\" class=\"style10\">\n"
            + "            <p class=\"style8\"><br>\n"
            + "              <span class=\"style9\">:##:</span><span class=\"dingbat\">              <label></label>\n"
            + "              <label></label>\n"
            + "              <label>              </label>\n"
            + "              </span><br>            \n"
            + "            </p>\n"
              + " <P align=\"center\" class=\"style20\"><A href=\"javascript:window.location.replace('/Recepttura');\" >"
               + "Vissza a főoldalra</A></P>"
            + "            \n"
            + "            <p class=\"style8\"><br>            \n"
            + "            </p>\n"
            + "          </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "    <table width=\"1093\" height=\"41\" border=\"1\" align=\"center\" bgcolor=\"#55DFFF\">\n"
            + "        <tr>\n"
            + "            <td width=\"1091\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "                    <div align=\"center\">FIGYELMEZTETÉS</div>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //---------------beregisztralva
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Beregisztrálva</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "</head>\n"
            + "<body> <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "          <br>\n"
            + "          <span class=\"style8\">Regisztált felhasználóknak személyes receptadatbázis, saját alapanyagadatbázis kialakításának, megosztásának lehetőségével </span><br>\n"
            + "        </p>\n"
            + "    </div>\n"
            + "    <table width=\"1091\" height=\"144\" border=\"3\" align=\"center\" bordercolor=\"#CCCC99\" bgcolor=\"#AA9F55\">\n"
            + "      <tr>\n"
            + "        <td width=\"1077\" height=\"134\"><table width=\"1059\" height=\"101\" border=\"2\" align=\"center\" bordercolor=\"#2A0000\">\n"
            + "            <tr>\n"
            + "              <td width=\"174\" height=\"97\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p class=\"style4\"> Információk</p>\n"
            + "                  <form name=\"form5\" method=\"post\" action=\"info\">\n"
            + "                    <label>\n"
            + "                    <input name=\"info\" type=\"submit\" class=\"sidebarHeader\" id=\"info\" tabindex=\"5\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"198\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Online kalkulátorok</p>\n"
            + "                  <form name=\"form4\" method=\"post\" action=\"kalk\">\n"
            + "                    <label>\n"
            + "                    <input name=\"kalk\" type=\"submit\" class=\"sidebarHeader\" id=\"kalk\" tabindex=\"4\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"199\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Segédanyagok </p>\n"
            + "                  <form name=\"form3\" method=\"post\" action=\"segedlet\">\n"
            + "                    <p>\n"
            + "                      <label>\n"
            + "                      <input name=\"alkalmazasok\" type=\"submit\" class=\"sidebarHeader\" id=\"alkalmazasok\" tabindex=\"3\" value=\"Tovább\">\n"
            + "                      </label>\n"
            + "                    </p>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"230\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Keresés az adatbázisban </p>\n"
            + "                  <form name=\"form2\" method=\"post\" action=\"keresesek\">\n"
            + "                    <label>\n"
            + "                    <input name=\"kereses\" type=\"submit\" class=\"sidebarHeader\" id=\"kereses\" tabindex=\"2\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "              <td width=\"222\" class=\"navLink\"><div align=\"center\" class=\"style4\">\n"
            + "                  <p> Regisztráció</p>\n"
            + "                  <form name=\"form1\" method=\"post\" action=\"Login\">\n"
            + "                    <label>\n"
            + "                    <input name=\"login\" type=\"submit\" class=\"sidebarHeader\" id=\"regisztralas\" tabindex=\"1\" value=\"Tovább\">\n"
            + "                    </label>\n"
            + "                  </form>\n"
            + "              </div></td>\n"
            + "            </tr>\n"
            + "        </table></td>\n"
            + "      </tr>\n"
            + "    </table>\n"
            + "    <br>\n"
            + "	\n"
            + "    <table width=\"847\" border=\"5\" align=\"center\" cellpadding=\"5\" bordercolor=\"#AA9F55\" bgcolor=\"#FFFF99\"  background=\"img/IMG_4108.JPG\">\n"
            + "        <tr bgcolor=\"#AA0000\">\n"
            + "            <th width=\"402\" height=\"503\" nowrap bgcolor=\"#AA9F55\" background=\"img/IMG_4108.JPG\"><div align=\"right\">\n"
            + "             \n"
            + "              </p>\n"
            + "                <table width=\"385\" height=\"486\" border=\"1\" align=\"left\">\n"
            + "                          <tr>\n"
            + "                            <td width=\"375\" bgcolor=\"#90EE90\"><div align=\"center\"><span class=\"sidebarHeader\">Az ön által megadott regisztrációs adatok:</span></div></td>\n"
            + "                          </tr>\n"
            + "                          <tr>\n"
            + "                            <td height=\"414\"><div align=\"right\"><span class=\"sidebarFooter\">Email címe:\n"
            + "                                  <label>\n"
            + "                                  <input name=\"textfield\" type=\"text\" value=\":##:RN\">\n"
            + "                                  </label>\n"
            + "                            <br>\n"
            + "							  Login(falhasználói) neve:\n"
            + "							  <input name=\"textfield\" type=\"text\" value=\":##:EC\">\n"
            + "							  <br>\n"
            + "						    Webcíme : </span>\n"
            + "                                <input name=\"textfield\" type=\"text\" value=\":##:WA\">\n"
            + "								<br>\n"
            + "								<br>\n"
            + "								<span class=\"sidebarFooter\">Egyéb megadott információk:</span>							  </div>\n"
            + "															  <label>\n"
            + "								<textarea name=\"textarea\" cols=\"50\" rows=\"11\">:##:EI </textarea>\n"
            + "							</label></td>\n"
            + "                          </tr>\n"
            + "              		</table>\n"
            + "                        <p align=\"center\">\n"
            + "                          <label></label>\n"
            + "                        </p>\n"
            + "          </div></th>\n"
            + "            <td width=\"415\" bgcolor=\"#F0F0F0\" >\n"
            + "              <div align=\"center\">\n"
            + "                <table width=\"421\" height=\"512\" border=\"1\" align=\"left\">\n"
            + "\n"
            + "                  <tr>\n"
            + "                    <td width=\"100%\" height=\"62\" bgcolor=\"#AB0000\"><div align=\"center\" class=\"sidebarHeader\">A regisztráció kész </div></td>\n"
            + "                  </tr>\n"
            + "                  <tr>\n"
            + "                    <td bgcolor=\"#90EE90\"><div align=\"center\">\n"
            + "                      <p align=\"center\" class=\"sidebarHeader\"><br>\n"
            + "                      Üdvözöljük a regisztrált felhasználóink között <br>\n"
            + "                      <br>\n"
            + "                      </p>\n"
            + "                      <p align=\"center\" class=\"sidebarFooter\">\n"
            + "					    <br>\n"
            + "                        <span class=\"style11\">A regisztrációját az első belépéssel aktiválhatja. </span><br>\n"
            + "                        <br>\n"
            + "                        Amennyiben 24 órán belül nem aktiválja a regisztrációját, automatikusan törlésre kerül. <br>\n"
            + "                        <br>\n"
            + "                        A több mint 6 hónapig nem használt regisztrációkat is <br>\n"
            + "                        automatikusan töröljük. <br>\n"
            + "                        <br>\n"
            + "                        A bejelentkezett felhasználónak is lehetősége van a <br>\n"
            + "                        regisztráció törlésére,- egy gomb megnyomásával. A törölt <br>\n"
            + "                        regisztrációkat visszaállítani nem tudjuk. <br>\n"
            + "                        <br>\n"
            + "                      A megadott adatokat a későbbiekben bármikor módosíthatja. <br>\n"
            + "                      <br>\n"
            + "                      <br>\n"
            + "                      </p>\n"
            + "                      <p align=\"justify\">\n"
            + "                        <span class=\"style3\">\n"
            + "                        <label></label>\n"
            + "                        </span>\n"
            + "                        <label></label>\n"
            + "                        \n"
            + "                        <label></label>\n"
            + "                      </p>\n"
            + "                        <div align=\"center\">\n"
            + "                          <p>\n"
            + "                         \n"
            + "                          <form name=\"form7\" method=\"post\" action=\"/Recepttura\">\n"
            + "                            <div align=\"right\">\n"
            + "                                  <label><span class=\"style12\">Bejelentkezés, használatba vétel</span>                                  \n"
            + "                                  <input name=\"fooldal\" type=\"submit\" class=\"style9\" tabindex=\"7\" value=\"Bejelentkezés\">\n"
            + "                              </label>\n"
            + "                            </div>\n"
            + "                          </form>\n"
            + "                      </div>\n"
            + "                        <label>                        </label>\n"
            + "                    </div></td>\n"
            + "                  </tr>\n"
            + "                </table>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>\n"
            + "    <table width=\"1209\" height=\"41\" border=\"1\" align=\"center\">\n"
            + "        <tr>\n"
            + "            <td width=\"1199\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "                    <div align=\"center\">Regisztáció kész </div>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //-------------admin
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Admin</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "</head>\n"
            + "<body>\n"
            + "<div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "    <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "        <br>\n"
            + "        <br>    \n"
            + "  </p>\n"
            + "    </div>\n"
            + "    <table width=\"753\" height=\"447\" border=\"5\" align=\"center\" bordercolor=\"#AA9F55\" bgcolor=\"#DEDECA\">\n"
            + "        <tr bgcolor=\"#F0F0F0\">\n"
            + "          <td width=\"735\" height=\"433\" class=\"navLink\"><table width=\"735\" height=\"327\" border=\"0\" align=\"center\" bgcolor=\"#DEDECA\">\n"
            + "                    <tr>\n"
            + "                        <td width=\"725\" height=\"32\"><div align=\"center\" class=\"dingbat\">Adminisztráció</div></td>\n"
            + "                    </tr>\n"
            + "                    <tr>\n"
            + "                        <td height=\"289\" bordercolor=\"#F0F0F0\"><br>\n"
            + "                            <table width=\"326\" height=\"254\" border=\"5\" align=\"center\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#C0DCC0\" class=\"footer\">\n"
            + "                                <tr>\n"
            + "                                    <td width=\"319\" height=\"252\" bgcolor=\"#FFFF99\"><form name=\"form1\" method=\"post\" action=\"adminstat\">\n"
            + "										  <div align=\"right\">Login name\n"
            + "                                                <input name=\"textfield\" type=\"text\" tabindex=\"1\">\n"
            + "                                            <label><br>\n"
            + "                                          password\n"
            + "                                          <input name=\"pass\" type=\"password\" id=\"pass\" tabindex=\"2\">\n"
            + "                                            </label>\n"
            + "                                          </div>\n"
            + "                                        \n"
            + "                                        <p align=\"right\">\n"
            + "                                          <label></label>\n"
            + "                                          <input name=\"login\" type=\"submit\" class=\"title\" tabindex=\"3\" value=\"Login\">                                          \n"
            + "                                          </div>\n"
            + "                                      </form>	\n"
            + "                                          </p>\n"
            + "                                    </p>\n"
            + "</td>\n"
            + "                                </tr>\n"
            + "                          </table>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                </table>\n"
            + "          </td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "    <table width=\"1093\" height=\"41\" border=\"1\" align=\"center\" bgcolor=\"#55DFFF\">\n"
            + "        <tr>\n"
            + "            <td width=\"1091\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "              <div align=\"center\">Adminstrátorok beléptetés </div>\n"
            + "                </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "\n"
            + "</html>\n"
            + "", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //---------jelszóbekérés
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Jelszó bekérés</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "		 <script type=\"text/javascript\" src=\"scr/pass.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"startTime();\">\n"
            + "<div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "    <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "        <br>\n"
            + "        <br>    \n"
            + "  </p>\n"
            + "</div>\n"
            + "    <table width=\"753\" height=\"447\" border=\"5\" align=\"center\" bordercolor=\"#AA9F55\" bgcolor=\"#DEDECA\">\n"
            + "        <tr bgcolor=\"#F0F0F0\">\n"
            + "          <td width=\"735\" height=\"433\" class=\"navLink\"><table width=\"735\" height=\"327\" border=\"0\" align=\"center\" bgcolor=\"#DEDECA\">\n"
            + "                    <tr>\n"
            + "                        <td width=\"725\" height=\"32\"><div align=\"center\" class=\"dingbat\">Felhasználó azonosítása.  </div></td>\n"
            + "                    </tr>\n"
            + "                    <tr>\n"
            + "                        <td height=\"341\" bordercolor=\"#F0F0F0\" background=\"img/IMG_4108.JPG\"><br>\n"
            + "                            </div>\n"
            + "                          <table width=\"326\" height=\"254\" border=\"5\" align=\"center\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#C0DCC0\" class=\"footer\">\n"
            + "                                <tr>\n"
            + "                                    <td width=\"319\" height=\"252\" bgcolor=\"#FFFF99\"><form name=\"form1\"  onsubmit=\"return validateForm()\" method=\"post\" action=\"bejelentkezve\">\n"
            + "										  <div align=\"center\"><span class=\"title\">Üdvözöljük :##:</span><span class=\"style4\"><br>\n"
            + "										  </span>\n"
            + "										    <p></p>\n"
            + "										    <span class=\"sidebarFooter\">Kérem, adja meg a jelszavát</span><span class=\"style4\">. </span>										    \n"
            + "										    <label>\n"
            + "										    <input name=\"HDID\" type=\"hidden\" value=\":###:\">\n"
            + "											<input name=\"HDTOKEN\" type=\"hidden\" value=\":#HDT#:\">\n"
            + "											<input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "										    <br>\n"
            + "                                            <span class=\"dingbat\"></span>                                          \n"
            + "											<p></p>\n"
            + "											<input name=\"pass\" type=\"password\" id=\"pass\" tabindex=\"1\" autofocus >\n"
            + "											<div id=\"visszadob\"></div>\n"
            + "											<div id=\"vers\"></div>                       \n"
            + "                    					</label>\n"
            + "                                      </div>\n"
            + "                                        \n"
            + "                                        <p align=\"center\">\n"
            + "                                          <label></label>\n"
            + "                                          <input name=\"login\" type=\"submit\" class=\"title\" tabindex=\"2\" value=\"Ellenörzés\">                                          \n"
            + "                                          </div>\n"
            + "                                      </form>	\n"
            + "                                      </p>\n"
            + "                                    </p>\n"
            + "								</td>\n"
            + "                                </tr>\n"
            + "                          </table>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                </table>\n"
            + "            <br><div align=\"center\" id=\"txt\"></div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <p>&nbsp;</p>\n"
            + "    <p>&nbsp;</p>\n"
            + "    <p>&nbsp;</p>\n"
            + "    <p><br>    \n"
            + "    </p>\n"
            + "    <table width=\"1093\" height=\"41\" border=\"1\" align=\"center\" bgcolor=\"#55DFFF\">\n"
            + "        <tr>\n"
            + "            <td width=\"1091\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "              <div align=\"center\">Regisztrált felhasználók beléptetése</div>\n"
            + "                </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //----------------receptfelvitel
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Recept felvitel</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "<script type=\"text/javascript\" src=\"scr/recept.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"setCounter();\" onunload=\"setCounter();\">\n"
            + "    <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "</div>\n"
            + "   <table width=\"709\" border=\"4\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#AA9F55\">\n"
            + "        <tr>\n"
            + "          <td width=\"619\" bordercolor=\"#90EE90\" \" class=\"\"><div align=\"center\">\n"
            + "            <form name=\"form3\" method=\"post\" action=\"bejelentkezve\">\n"
            + "              <label>\n"
            + "              <input name=\"Submit\" type=\"submit\" class=\"style9\" value=\"Vissza a profilomhoz, mégsem\">\n"
            + "              <input name=\"idr\" type=\"hidden\"  value=\":#ID#:\">\n"
            + "              <input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "              <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "              <input name=\"honnan\" type=\"hidden\" value=\"RFV\">\n"
            + "              </label>\n"
            + "            </form>\n"
            + "            <p align=\"center\" class=\"sidebarHeader\">            Recept felvétele, alapadatok megadása </p>\n"
            + "            <div class=\"nav\" id=\"belepett\"><span class=\"big\">A rendszer 20 perc után automatikusan kilépteti ha nem végez műveletet. A nem mentett módosítások elvesznek. </span></div><div class=\"sidebarHeader\" id=\"txt\"></div>\n"
            + "           <form action=\"recepttemp\" method=\"post\"  onsubmit=\"return validateForm()\" name=\"form6\" >\n"
            + "            <p align=\"center\" class=\"sidebarFooter\">&nbsp;</p>\n"
            + "            <p align=\"center\">\n"
            + "              <span class=\"subtitle\">\n"
            + "              <label class=\"subtitle\">Étel elnevezése\n"
            + "              <input type=\"text\" name=\"etelneve\" tabindex=\"1\" autoselect>\n"
            + "              <br>\n"
            + "              <br>\n"
            + "              Ételkategória (válasszon)\n"
            + "              <select name=\"etelkategoria\" tabindex=\"2\">\n"
            + "                \n"
            + "			  :#VEK#:\n"
            + "              \n"
            + "              </select>\n"
            + "              </label>\n"
            + "             </span></p>\n"
            + "            <p align=\"center\"><span class=\"subtitle\">\n"
            + "              <label>Hány személyre (válassza ki)\n"
            + "              <select name=\"szemelyre\" tabindex=\"3\">\n"
            + "                <option value=\"4\" selected>4</option>\n"
            + "                <option value=\"2\">2</option>\n"
            + "                <option value=\"3\">3</option>\n"
            + "                <option value=\"1\">1</option>\n"
            + "				<option value=\"6\">6</option>\n"
            + "                <option value=\"8\">8</option>\n"
            + "                <option value=\"10\">10</option>\n"
            + "				<option value=\"12\">12</option>\n"
            + "              </select>\n"
            + "              </label>\n"
            + "              <label class=\"subtitle\"></label>\n"
            + "            </span></p>\n"
            + "            <p align=\"center\">\n"
            + "              <label class=\"subtitle\">Elkészítési idő (perc)</label>\n"
            + "              <label>\n"
            + "              <select name=\"elkeszitesiido\" tabindex=\"4\">\n"
            + "                <option value=\"5\">5 perc</option>\n"
            + "                <option value=\"10\">10 perc</option>\n"
            + "                <option value=\"15\">15 perc</option>\n"
            + "                <option value=\"20\">20 perc</option>\n"
            + "                <option value=\"30\">30 perc</option>\n"
            + "                <option value=\"45\">45 perc</option>\n"
            + "                <option value=\"60\">1 óra</option>\n"
            + "                <option value=\"90\">1,5 óra</option>\n"
            + "                <option value=\"120\">2 óra</option>\n"
            + "                <option value=\"150\">2,5 óra</option>\n"
            + "                <option value=\"180\">3 óra</option>\n"
            + "                <option value=\"240\">4 óra</option>\n"
            + "                <option value=\"300\">5 óra</option>\n"
            + "                <option value=\"400\">több mint 5 óra</option>\n"
            + "              </select>\n"
            + "</label><span class=\"subtitle\">\n"
            + "                <label class=\"subtitle\"></label>\n"
            + "            </span>\n"
            + "              <label class=\"subtitle\">\n"
            + "            <input type=\"hidden\" name=\"idr\" value=\":#ID#:\">\n"
            + "            <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "			<input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "			\n"
            + "              </label>\n"
            + "            </p>\n"
            + "            <p align=\"center\" class=\"subtitle\">\n"
            + "              <label>Ha megadta az alapinformációkat akkor nyomja meg a gombot </label></p>\n"
            + "          <label>\n"
            + "              <input name=\"Submit\" type=\"submit\" class=\"style9\" tabindex=\"5\" value=\"Receptfejléc rögzítése\">\n"
            + "              <br>\n"
            + "              <br>\n"
            + "             </label>\n"
            + "           </form>\n"
            + "		    </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //-------bejelentkezve
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Bejelentkezve</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "    <script type=\"text/javascript\" src=\"scr/belepve.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"setCounter();\" onunload=\"setCounter();\">\n"
            + "\n"
            + "\n"
            + "    <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "            <br>\n"
            + "            <br>\n"
            + "      </p>\n"
            + "    </div>\n"
            + "    <table width=\"838\" height=\"144\" border=\"3\" align=\"center\" bordercolor=\"#CCCC99\" bgcolor=\"#AA9F55\" class=\"style8\">\n"
            + "        <tr>\n"
            + "            <td width=\"824\" height=\"134\"><div align=\"center\" class=\"footer\">\n"
            + "              <p class=\"subtitle\"><br>\n"
            + "              :#BFH#: be van jelentkezve </p>\n"
            + "              <span class=\"subtitle\">\n"
            + "              <div class=\"sidebarFooter\" id=\"belepett\"></div>\n"
            + "              <div id=\"txt\"></div>\n"
            + "              </span><br>\n"
            + "              <br>\n"
            + "              <form name=\"form1\" method=\"post\" action=\"logout\">\n"
            + "                <label>\n"
            + "                <input name=\"Submit\" type=\"submit\" class=\"subtitle\" value=\"Kijelentkezés\">\n"
            + "				 <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "				 <input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "                </label>\n"
            + "              </form>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "     <table width=\"1188\" border=\"0\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#AA9F55\" bgcolor=\"#DEDECA\" class=\"none\">\n"
            + "        <tr bgcolor=\"#F0F0F0\">\n"
            + "          <td width=\"1187\" height=\"\" bordercolor=\"#F0F0F0\" bgcolor=\"#F0F0F0\" class=\"titlebar\" ><div align=\"center\">\n"
            + "            <table width=\"1120\" height=\"133\" border=\"3\" align=\"left\" bgcolor=\"#DEDECA\" class=\"subtitle\">\n"
            + "              <tr>\n"
            + "                <td width=\"507\" class=\"navLink\"><br>Receptet állítok össze. <br></td>\n"
            + "                <td width=\"72\" bgcolor=\"#336699\"><form name=\"recept\" method=\"post\" action=\"RR\">\n"
            + "                  <label>\n"
            + "                  <input name=\"Submit\" type=\"submit\" class=\"subtitle\" tabindex=\"1\" value=\"Tovább\">\n"
            + "                  <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "				  <input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "				</label>\n"
            + "                </form></td>\n"
            + "                <td width=\"515\"><div align=\"right\" class=\"navLink\">A saját recptjeim száma: :#SRSZ#: </div></td>\n"
            + "              </tr>\n"
            + "              <tr>\n"
            + "                <td class=\"navLink\"><br>Az eddig rögzített receptjeimben keresek . </td>\n"
            + "                <td bgcolor=\"#336699\"><form name=\"kereses\" method=\"post\" action=\"recep_keresese\">\n"
            + "                  <label>\n"
            + "                  <input name=\"Submit\" type=\"submit\" class=\"subtitle\" tabindex=\"1\" value=\"Keresés\">\n"
            + "                  <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "                  <input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "                  </label>\n"
            + "                </form></td>\n"
            + "                <td><div align=\"right\">\n"
            + "                  <label>\n"
            + "                  <span class=\"navLink\">\n"
            + "				<input type=\"checkbox\" name=\"mindenreceptben\" value=\"0\">\n"
            + "					<span class=\"navLink\">Keresek mindenki nyilvános receptjeiben\n"
            + "                    </span>				  \n"
            + "					<div></div>   <span class=\"navLink\">Kulcsszó</span>                  <input type=\"text\" name=\"textfield\">\n"
            + "                  </label>\n"
            + "                </div></td>\n"
            + "              </tr>\n"
            + "              <tr>\n"
            + "                <td class=\"navLink\"><br>Alapanyagot veszek fel.<br></td>\n"
            + "                <td bgcolor=\"#336699\"><form name=\"falapanyagaim\" method=\"post\" action=\"alapanyag_rogzitese\">\n"
            + "                  <label>\n"
            + "                  <input name=\"Submit\" type=\"submit\" class=\"subtitle\" tabindex=\"1\" value=\"Tovább\">\n"
            + "                  <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "                  <input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "                  </label>\n"
            + "                </form></td>\n"
            + "                <td><div align=\"right\" class=\"navLink\">Az elérhető alapanyagok száma: :#SASZ#: </div></td>\n"
            + "              </tr>\n"
            + "              <tr>\n"
            + "                <td class=\"navLink\"><br>Ezek vannak otthon mit főzzek ? <br></td>\n"
            + "                <td bgcolor=\"#336699\"><form name=\"lekerdezes\" method=\"post\" action=\"specialis_keresesek\">\n"
            + "                  <label>\n"
            + "                  <input name=\"Submit\" type=\"submit\" class=\"subtitle\" tabindex=\"1\" value=\"Tovább\">\n"
            + "                  <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "                  <input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "                  </label>\n"
            + "                </form></td>\n"
            + "             <td>&nbsp;</td>\n"
            + "              </tr>\n"
            + "            </table>\n"
            + "          </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "    <table width=\"1093\" height=\"41\" border=\"1\" align=\"center\" bgcolor=\"#55DFFF\">\n"
            + "        <tr>\n"
            + "            <td width=\"1091\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "              <div align=\"center\">Bejelentkezett felhasználó: :#BFH#:\n"
            + "			  <form name=\"form2\" method=\"post\" action=\"unreg\">\n"
            + "			    <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "<input name=\"id\" type=\"hidden\" value=\":#LOGID#:\">                \n"
            + "<label>\n"
            + "                        <input type=\"submit\" name=\"Submit\" value=\"Regisztrációm törlése\">\n"
            + "                </label>\n"
            + "                </form>\n"
            + "                    </div>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n"
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Kérdés</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "	 <script type=\"text/javascript\" src=\"scr/kerdes_oldal.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"startTime();\"  onunload=\"stop();\">\n"
            + "    <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "            <br>\n"
            + "            <span class=\"style8\">Regisztált felhasználóknak személyes receptadatbázis, saját alapanyagadatbázis kialakításának, megosztásának lehetőségével </span><br>\n"
            + "      </p>\n"
            + "    </div>\n"
            + "    <br>    \n"
            + "     <table width=\"845\" height=\"500\" border=\"0\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#AA9F55\" bgcolor=\"#DEDECA\">\n"
            + "        <tr bgcolor=\"#F0F0F0\">\n"
            + "          <td width=\"827\" height=\"433\" bordercolor=\"#D40000\" bgcolor=\"#990000\" class=\"style8\"><div align=\"center\" class=\"style10\">\n"
            + "            <p class=\"style8\"><br>\n"
            + "              <span class=\"style9\">:##:              \n"
            + "              <label></label>\n"
            + "              <label></label>\n"
            + "              <label></label>\n"
            + "              </span><br>\n"
            + "            </p>\n"
            + "            <form name=\"form6\" onsubmit=\"return validateForm()\" method=\"post\" action=\":#HOVAKULDI#:\">\n"
            + "              <label class=\"navLink style15\"><br>\n"
            + "              HA A VÁLASZA <span class=\"title\">IGEN</span>  AKKOR JELÖJE BE </label>\n"
            + "              <input name=\"valasz\" type=\"checkbox\">\n"
            + "              <br>\n"
            + "              <label>\n"
            + "             <input name=\"Submit\" type=\"submit\" class=\"style13\" id=\"fooldalra\" value=\"VÁLASZ KÜLDÉSE\">\n"
            + "             <br>\n"
            + "             <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "<input name=\"parameter\" type=\"hidden\" value=\":#parameter#:\">\n"
            + "<input name=\"torol\" type=\"hidden\" value=\":#torol#:\">\n"
            + "			</label>\n"
            + "		    </form>\n"
            + "            <p class=\"style8\"><br>\n"
            + "<div align=\"center\" id=\"elkuldve\"></div>            \n"
            + "            </p>\n"
            + "          </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "    <table width=\"1093\" height=\"41\" border=\"1\" align=\"center\" bgcolor=\"#55DFFF\">\n"
            + "        <tr>\n"
            + "            <td width=\"1091\" height=\"35\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"footer\">\n"
            + "\n"
            + "                    <div align=\"center\" id=\"txt\"></div>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n"
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Recept felvitel</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "<script type=\"text/javascript\" src=\"scr/recept2.js\"></script>\n"
            + "</head>\n"
            + "<body onload=\"setCounter();\" onunload=\"setCounter();\">\n"
            + "    <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "</div>\n"
            + "        <table width=\"818\" border=\"4\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#999933\">\n"
            + "        <tr>\n"
            + "          <td width=\"738\" \" class=\"\"><div align=\"center\">\n"
            + "            <form name=\"form3\" method=\"post\" action=\"bejelentkezve\" onsubmit=\"return vissza()\" >\n"
            + "              <label>\n"
            + "              <input name=\"Submit\" type=\"submit\" class=\"style9\" value=\"Vissza a profilomhoz, változások mentése\">\n"
            + "              <input name=\"idr\" type=\"hidden\"  value=\":#ID#:\">\n"
            + "              <input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "              <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "              <input name=\"honnan\" type=\"hidden\" value=\"RFV\">\n"
            + "<input name=\"etelnev\" type=\"hidden\" id=\"etelnev\" value=\":#ENEVE#:\">\n"
            + "<div id=\"leiras\"></div>\n"
            + "              </label>\n"
            + "            </form>\n"
            + "            <p align=\"center\" class=\"sidebarHeader\">            Alapanyagok recepthez adása</p>\n"
            + "            <div class=\"nav\" id=\"belepett\"><span class=\"big\">A rendszer 20 perc után automatikusan kilépteti ha nem végez műveletet. A nem mentett módosítások elvesznek. </span></div><div class=\"sidebarHeader\" id=\"txt\"></div>\n"
            + "           <form action=\"alapanyag_rogzitese\" method=\"post\"  onsubmit=\"return validateForm()\" name=\"alapanyag_hozzaadas\" >\n"
            + "            <p align=\"center\" class=\"sidebarFooter\">&nbsp;</p>\n"
            + "            <p align=\"center\">\n"
            + "              <span class=\"subtitle\">\n"
            + "              <label class=\"subtitle\">Étel elnevezése</label>\n"
            + "              : \n"
            + "             :#ENEVE#: <br>\n"
            + "             kategoria: :#EKAT#:</span></p>\n"
            + "			 <p class=\"sidebarFooter\">\n"
            + "               <input name=\"etelneve\" type=\"hidden\" value=\":#ENEVE#:\">\n"
            + "               <input name=\"kategoria\" type=\"hidden\" value=\":#EKAT#:\">\n"
            + "             Adja a recepthez az alapanyagokat </p>\n"
            + "			 <p align=\"center\"><span class=\"subtitle\">Alapanyag (válasszon)\n"
            + "                <select name=\"alapanyaflista\" tabindex=\"1\" autofokus>\n"
            + "               	:#VA#:\n"
            + "                </select>\n"
            + "            </span></p>\n"
            + "            <p align=\"center\"><span class=\"subtitle\">\n"
            + "              <label class=\"subtitle\">\n"
            + "              Alapanyag mennyisége\n"
            + "              <input name=\"mennyisege\" type=\"text\" id=\"mennyisege\"  size=\"4\" tabindex=\"2\">\n"
            + "              <br>\n"
            + "			</label></span><span class=\"subtitle\">\n"
            + "            <label><br>\n"
            + "              Mennyiségi egysége\n"
            + "              <select name=\"mennyisegiegyseg\" id=\"mennyisegiegyseg\" tabindex=\"3\">\n"
            + "			  :#VME#:\n"
            + "              </select>\n"
            + "              </label>\n"
            + "              <label class=\"subtitle\"></label>\n"
            + "            </span></p>\n"
            + "            <p align=\"center\">\n"
            + "              <label class=\"subtitle\"></label>\n"
            + "              <label></label>\n"
            + "              <span class=\"subtitle\">\n"
            + "                <label class=\"subtitle\"></label>\n"
            + "            </span>\n"
            + "              <label class=\"subtitle\">\n"
            + "            <input type=\"hidden\" name=\"idr\" value=\":#ID#:\">\n"
            + "            <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "			<input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "			\n"
            + "              </label>\n"
            + "              <label>\n"
            + "              <input name=\"honnan\" type=\"hidden\" value=\"RFV\">\n"
            + "              </label>\n"
            + "            </p>\n"
            + "            <p align=\"center\">              <label>\n"
            + "              <input name=\"Submit\" type=\"submit\" class=\"sidebarHeader\" tabindex=\"5\" value=\"Alapanyag hozzáadása\">\n"
            + "              </label>\n"
            + "            </p>\n"
            + "            <p align=\"center\" class=\"sidebarFooter\">  \n"
            + "              <label></label>\n"
            + "            </p>\n"
            + "            <p>\n"
            + "              <label><span class=\"nav\">Elkészítés leírása van 3000 karakternyi hely </span>                 <br>\n"
            + "                <textarea id=\"textarea\" name=\"textarea\" cols=\"88\" rows=\"10\"></textarea>\n"
            + "                <br>\n"
            + "</label>\n"
            + "            </p>\n"
            + "           </form>\n"
            + "			 \n"
            + "            <p class=\"title\">Rögzített alapanyagok </p>\n"
            + "            <p class=\"sidebarFooter\">:#AALISTA#:\n"
            + "              <label>              </label>\n"
            + "            </p>\n"
            + "            <form action=\"rtorolk\" method=\"post\" name=\"rtf\">\n"
            + "               <label>\n"
            + "               <input name=\"Submit\" type=\"submit\" class=\"title\" value=\"A recept törlése\">\n"
            + "			   </label>\n"
            + "               <label class=\"subtitle\">\n"
            + "               <input type=\"hidden\" name=\"id\" value=\":#ID#:\">\n"
            + "               <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "               <input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "               </label>\n"
            + "               <label>\n"
            + "               <input name=\"recepttorlese\" type=\"hidden\" value=\":#ENEVE#:\">\n"
            + "               </label>\n"
            + "               <label>               </label>\n"
            + "            </form>\n"
            + "             <p class=\"sidebarHeader\">&nbsp;</p>\n"
            + "             </div></td>\n"
            + "        </tr>\n"
            + "</table>", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n"
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Recept keresés</title>\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "<script type=\"text/javascript\"> </script>\n"
            + "</head>\n"
            + "<body>\n"
            + "        <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "            <br>\n"
            + "            <br>\n"
            + "      </p>\n"
            + "    </div>\n"
            + "    <table width=\"838\" height=\"144\" border=\"3\" align=\"center\" bordercolor=\"#CCCC99\" bgcolor=\"#AA9F55\" class=\"style8\">\n"
            + "        <tr>\n"
            + "            <td width=\"824\" height=\"134\"><div align=\"center\" class=\"footer\">\n"
            + "              <p class=\"subtitle\">Az ön álltal rögzített receptek</p>\n"
            + "              <span class=\"subtitle\">\n"
            + "              <div class=\"sidebarFooter\" id=\"belepett\"></div>\n"
            + "              <div id=\"txt\"></div>\n"
            + "              </span><br>\n"
            + "              <form name=\"form3\" method=\"post\" action=\"bejelentkezve\">\n"
            + "                <label>\n"
            + "                <input name=\"Submit\" type=\"submit\" class=\"style9\" value=\"Vissza a profilomhoz\">\n"
            + "                <input name=\"idr\" type=\"hidden\"  value=\":#ID#:\">\n"
            + "                <input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "                <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "                <input name=\"honnan\" type=\"hidden\" value=\"RFV\">\n"
            + "</label>\n"
            + "                            </form>\n"
            + "              <br>\n"
            + "              <form name=\"form1\" method=\"post\" action=\"logout\">\n"
            + "                <label>\n"
            + "                <input name=\"Submit\" type=\"submit\" class=\"subtitle\" value=\"Kijelentkezés\">\n"
            + "				 <input name=\"logtempid\" type=\"hidden\" value=\":#LOGOUT#:\">\n"
            + "				 <input name=\"id\" type=\"hidden\" id=\"id\" value=\":#LOGID#:\">\n"
            + "                </label>\n"
            + "              </form>\n"
            + "            </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "     <table width=\"1188\" border=\"6\" align=\"center\" cellpadding=\"20\" cellspacing=\"20\" bordercolor=\"#FFFF00\" class=\"style12\">\n"
            + "        <tr>\n"
            + "          <td width=\"1187\" height=\"\" bordercolor=\"#FFFF99\" ><div align=\"center\">\n"
            + "            <p class=\"title\">Keresések </p>\n"
            + "            <form name=\"form2\" method=\"post\" action=\"recep_keresese\">\n"
            + "              <div align=\"left\">\n"
            + "                <span class=\"dingbat\">\n"
            + "                <div align=\"right\" class=\"footer\">\n"
            + "                  <label>\n"
            + "                  Válasszon ételkategóriát                \n"
            + "                  <select name=\"etelkategoria\" class=\"legal\">\n"
            + "                    \n"
            + "				:#EKAT#:\n"
            + "                \n"
            + "                \n"
            + "                  \n"
            + "                  </select>\n"
            + "                  </label>\n"
            + "                  <br>\n"
            + "                  <strong class=\"footer\">Az étel nevében szerepelhet</strong>                \n"
            + "                  <label class=\"style12\">\n"
            + "                  <input type=\"text\" name=\"etelneve\">\n"
            + "                  <br>\n"
            + "                  </label>\n"
            + "                  <strong class=\"footer\">Az étel alapanyagaiban szerepelhet</strong>                \n"
            + "                  <input type=\"text\" name=\"alapanyag\">\n"
            + "                  <br>\n"
            + "                  <strong class=\"footer	\">Az elkészítés leírásában szereplhet</strong>\n"
            + "                  <input type=\"text\" name=\"leiras\">\n"
            + "                  <br>\n"
            + "                  <label>\n"
            + "                  <input name=\"Submit\" type=\"submit\" class=\"title\" value=\"Keresés indítása\">\n"
            + "                  </label>\n"
            + "                </div>\n"
            + "                <label class=\"title\">                  </label>\n"
            + "              </div>\n"
            + "              <label class=\"title\">\n"
            + "              <input name=\"id\" type=\"hidden\"  value=\":#ID#:\">\n"
            + "              <input name=\"logtempid\" type=\"hidden\" value=\":#LOGID#:\">\n"
            + "              <input name=\"atok\" type=\"hidden\" value=\":#ATOK#:\">\n"
            + "              <input name=\"honnan\" type=\"hidden\" value=\"RFV\">\n"
            + "</label>\n"
            + "              <label class=\"style12\">\n"
            + "              </label>\n"
            + "            </form>\n"
            + "            <p class=\"footer\">:#LEKE#:</p>\n"
            + "          </div></td>\n"
            + "        </tr>\n"
            + "</table>\n"
            + "    <br>    \n"
            + "</body>\n"
            + "</html>","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//HU\">\n" //alapfejléc
            + "    <html>\n"
            + "<head>\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <title>Recepttura</title>\n"
            + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
            + "    <link rel=\"stylesheet\" href=\"css/alap.css\">    \n"
            + "   <style type=\"text/css\">\n"
            + "       -->  \n"
            + "        body{\n"
            + "            :#K#:KEPET\n"
            + "        }\n"
            + "        <--\n"
            + "    </style>\n"
            + "    <script type=\"text/javascript\"></script>\n"
            + "</head>\n"
            + "<body \">\n"
            + "   <div align=\"center\">\n"
            + "        <p>&nbsp;</p>\n"
            + "        <p><span class=\"style6\">Ételreceptek, alapanyagok, beltartalmi értékekek, online kalkulációk </span><br>\n"
            + "          <br>\n"
            + "          <span class=\"style8\">Regisztált felhasználóknak személyes receptadatbázis, saját alapanyagadatbázis kialakításának, megosztásának lehetőségével </span><br>\n"
            + "        </p>\n"};

        return taroltoldal[szama];
    }

}
